In [1]:
import numpy as np
import sys
from numpy import linalg
import matplotlib.pyplot as plt

In [24]:
#Fatoração LU
ordem = int(input('determine a ordem  da matriz: ')) # ordem da matriz
A = np.zeros((ordem,ordem))
N = 100
for i in range(ordem):
    for j in range(ordem):
        A[i,j]=float(input('A'+str(i)+str(j)+'='))
print(A)
if np.linalg.det(A) ==0:
    sys.exit('DET =0, Matriz Singular ou possui Equações Linearmente Dependentes')    
print('det A: ', np.linalg.det(A))
B = np.zeros(ordem)
for i in range(ordem):
    B[i]=float(input('B'+str(i)+'='))
print(B)
# Triangulaçao da matriz LU
mult = 0
i=0
L = np.eye(ordem)
U = np.copy(A)
while i<ordem-1:
    j=i+1
    while j<ordem:
        mult = U[j,i]/U[i,i]
        print('Multiplicador: ',mult)
        L[j,i] = mult
        for k in range(ordem):
            U[j,k] = U[j,k] - U[i,k]*mult  
        U[j,i]=0
        j +=1
    print('L:',L)
    print('U:',U)
    print()
    i+=1

# Resolução
Y = np.zeros(ordem)
Y = np.linalg.solve(L,B)
print('Y: ',Y)

X = np.zeros(ordem)
X = np.linalg.solve(U,Y)
print('X: ',X)

determine a ordem  da matriz: 4
A00=2
A01=1
A02=1
A03=0
A10=4
A11=3
A12=3
A13=1
A20=8
A21=7
A22=9
A23=5
A30=6
A31=7
A32=9
A33=8
[[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]
det A:  7.999999999999998
B0=1
B1=2
B2=4
B3=5
[1. 2. 4. 5.]
Multiplicador:  2.0
Multiplicador:  4.0
Multiplicador:  3.0
L: [[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 0. 1. 0.]
 [3. 0. 0. 1.]]
U: [[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 3. 5. 5.]
 [0. 4. 6. 8.]]

Multiplicador:  3.0
Multiplicador:  4.0
L: [[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 0. 1.]]
U: [[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 2. 4.]]

Multiplicador:  1.0
L: [[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]
U: [[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]

Y:  [ 1.  0. -0.  2.]
X:  [ 1.  0. -1.  1.]


In [35]:
#Fatoração LU com Pivoteamento Parcial
ordem = int(input('determine a ordem  da matriz: ')) # ordem da matriz
A = np.zeros((ordem,ordem))
N = 100
for i in range(ordem):
    for j in range(ordem):
        A[i,j]=float(input('A'+str(i)+str(j)+'='))
print(A)
if np.linalg.det(A) ==0:
    sys.exit('DET =0, Matriz Singular ou possui Equações Linearmente Dependentes')    
print('det A: ', np.linalg.det(A))
B = np.zeros(ordem)
for i in range(ordem):
    B[i]=float(input('B'+str(i)+'='))
print(B)
# Triangulaçao da matriz LU
mult = 0
i=0
P = np.eye(ordem)
L = np.eye(ordem)
U = np.copy(A)
k=0
while k< ordem:
    piv = np.argmax(abs(U[k:,0]))+k
    if piv != k:
        print('Pivoteamento')
        P[[k, piv]] = P[[piv, k]]
        B[[k, piv]] = B[[piv, k]]
        U[[k, piv]] = U[[piv, k]]
    k+=1
print('P:',P)
print('A:',U)
    
while i<ordem-1:
    j=i+1
    while j<ordem:
        mult = U[j,i]/U[i,i]
        print('Multiplicador: ',mult)
        L[j,i] = mult
        for k in range(ordem):
            U[j,k] = U[j,k] - U[i,k]*mult  
        U[j,i]=0
        j +=1
    print('L:',L)
    print('U:',U)
    print()
    i+=1

# Resolução
Y = np.zeros(ordem)
Y = np.linalg.solve(L,B)
print('Y: ',Y)

X = np.zeros(ordem)
X = np.linalg.solve(U,Y)
print('X: ',X)

determine a ordem  da matriz: 4
A00=2
A01=1
A02=1
A03=0
A10=4
A11=3
A12=3
A13=1
A20=8
A21=7
A22=9
A23=5
A30=6
A31=7
A32=9
A33=8
[[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]
det A:  7.999999999999998
B0=1
B1=2
B2=4
B3=5
[1. 2. 4. 5.]
Pivoteamento
Pivoteamento
Pivoteamento
P: [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
A: [[8. 7. 9. 5.]
 [6. 7. 9. 8.]
 [4. 3. 3. 1.]
 [2. 1. 1. 0.]]
Multiplicador:  0.75
Multiplicador:  0.5
Multiplicador:  0.25
L: [[1.   0.   0.   0.  ]
 [0.75 1.   0.   0.  ]
 [0.5  0.   1.   0.  ]
 [0.25 0.   0.   1.  ]]
U: [[ 8.    7.    9.    5.  ]
 [ 0.    1.75  2.25  4.25]
 [ 0.   -0.5  -1.5  -1.5 ]
 [ 0.   -0.75 -1.25 -1.25]]

Multiplicador:  -0.2857142857142857
Multiplicador:  -0.42857142857142855
L: [[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.          1.        ]]
U: [[ 8.          7.          9.