In [1]:
import numpy as np
import sys
from numpy import linalg
import matplotlib.pyplot as plt

In [14]:
#gauss_jacobi - com criterio de linhas
ordem = int(input('determine a ordem  da matriz: ')) # ordem da matriz
A = np.zeros((ordem,ordem))
N = 100
for i in range(ordem):
    for j in range(ordem):
        A[i,j]=float(input('A'+str(i)+str(j)+'='))
print(A)
if np.linalg.det(A) ==0:
    sys.exit('DET =0, Matriz Singular ou possui Equações Linearmente Dependentes')
    
print('det A: ', np.linalg.det(A))

#criterio de linha
alfa=np.zeros(ordem)
for i in range(ordem):
    alfa[i]=sum(A[i])
    alfa[i]=abs((alfa[i]-A[i,i])/abs(A[i,i]))
print('alfa: ',alfa)
if max(alfa)>1:
    sys.exit('Nao atende o critério das linhas')


B = np.zeros(ordem)
for i in range(ordem):
    B[i]=float(input('B'+str(i)+'='))
print(B)

# Vetor Inicial
X0=np.zeros(ordem)
for i in range(ordem):
    X0[i]=B[i]/A[i,i]
print('X0: ',X0)
tol = float(input('determine a tol do erro: '))
it = 0  
#iteracoes jacobi
X = np.zeros(ordem)
while it<100:
    it +=1
    for i in range(ordem):
        X[i] = B[i]
        for j in range(ordem):
            if j != i:
                X[i] -= A[i,j]*X0[j]
        X[i] /= A[i,i]
    print('X'+str(it)+'= ',X)
    erro = np.linalg.norm(X-X0,np.inf)
    errorel = np.linalg.norm(X-X0,np.inf)/abs(max(X))
    print('erro: ',erro)
    print('errorel: ',errorel)
    if erro<tol or errorel<tol:
        sys.exit('Criterio de Parada Atingido')
    X0= np.copy(X) 

determine a ordem  da matriz: 3
A00=5
A01=2
A02=2
A10=1
A11=3
A12=-1
A20=0
A21=6
A22=8
[[ 5.  2.  2.]
 [ 1.  3. -1.]
 [ 0.  6.  8.]]
det A:  146.0
alfa:  [0.8  0.   0.75]
B0=3
B1=-2
B2=-6
[ 3. -2. -6.]
X0:  [ 0.6        -0.66666667 -0.75      ]
determine a tol do erro: 0.001
X1=  [ 1.16666667 -1.11666667 -0.25      ]
erro:  0.5666666666666665
errorel:  0.48571428571428565
X2=  [ 1.14666667 -1.13888889  0.0875    ]
erro:  0.3375
errorel:  0.29433139534883723
X3=  [ 1.02055556 -1.01972222  0.10416667]
erro:  0.12611111111111106
errorel:  0.12357103973870436
X4=  [ 0.96622222 -0.97212963  0.01479167]
erro:  0.08937499999999998
errorel:  0.09249942502299906
X5=  [ 0.98293519 -0.98381019 -0.02090278]
erro:  0.03569444444444436
errorel:  0.03631413849298672
X6=  [ 1.00188519 -1.00127932 -0.01214236]
erro:  0.01894999999999991
errorel:  0.018914342960862585
X7=  [ 1.00536867e+00 -1.00467585e+00  9.59490741e-04]
erro:  0.013101851851851753
errorel:  0.013031887909186217
X8=  [ 1.00148654 -1.00

SystemExit: Criterio de Parada Atingido

In [17]:
#gauss_seidel- com criterio de sassenfeld
ordem = int(input('determine a ordem  da matriz: ')) # ordem da matriz
A = np.zeros((ordem,ordem))
N = 100
for i in range(ordem):
    for j in range(ordem):
        A[i,j]=float(input('A'+str(i)+str(j)+'='))
print(A)
if np.linalg.det(A) ==0:
    sys.exit('DET =0, Matriz Singular ou possui Equações Linearmente Dependentes')
    
print('det A: ', np.linalg.det(A))

#criterio de sassenfeld
beta=np.zeros(ordem)

for i in range(ordem):
    beta[i]= 0
    beta[i] = sum(A[i])-A[i][i]
    j=0
    while j < i:
        beta[i] -= A[i][j]
        beta[i] += A[i][j]*beta[j]
        j += 1
    beta[i] /= A[i][i]
print('beta: ',beta)
if max(beta)>1:
    sys.exit('Nao atende o critério de sassenfeld')


B = np.zeros(ordem)
for i in range(ordem):
    B[i]=float(input('B'+str(i)+'='))
print(B)

# Vetor Inicial
X0=np.zeros(ordem)
for i in range(ordem):
    X0[i]=B[i]/A[i,i]
print('X0: ',X0)
tol = float(input('determine a tol do erro: '))
it = 0
#iteracoes seidel
X = np.zeros(ordem)
X= np.copy(X0)
while it<100:
    it +=1
    for i in range(ordem):
        X[i] = B[i]
        for j in range(ordem):
            if j != i:
                X[i] -= A[i,j]*X[j]
        X[i] /= A[i,i]
    print('X'+str(it)+'= ',X)
    erro = np.linalg.norm(X-X0,np.inf)
    errorel = np.linalg.norm(X-X0,np.inf)/abs(max(X))
    print('erro: ',erro)
    print('errorel: ',errorel)
    if erro<tol or errorel<tol:
        sys.exit('Criterio de Parada Atingido')
    X0= np.copy(X) 

determine a ordem  da matriz: 3
A00=4
A01=1
A02=1
A10=1
A11=6
A12=1
A20=2
A21=1
A22=8
[[4. 1. 1.]
 [1. 6. 1.]
 [2. 1. 8.]]
det A:  171.00000000000009
beta:  [0.5     0.25    0.15625]
B0=3
B1=8
B2=11
[ 3.  8. 11.]
X0:  [0.75       1.33333333 1.375     ]
determine a tol do erro: 0.001
X1=  [0.07291667 1.09201389 1.2202691 ]
erro:  0.6770833333333333
errorel:  0.5548639516272452
X2=  [0.17192925 1.10130027 1.19435515]
erro:  0.09901258680555558
errorel:  0.08290045604714351
X3=  [0.17608614 1.10492645 1.19286266]
erro:  0.004156889738859915
errorel:  0.003484801633694682
X4=  [0.17555272 1.1052641  1.19295381]
erro:  0.0005334203625902978
errorel:  0.0004471425127569257


SystemExit: Criterio de Parada Atingido